# Shared environment for course lab scripts.
# shellcheck disable=SC2034

LABS_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Prefer SAM CLI from project venv if system sam is missing
if [[ -x "${LABS_ROOT}/.venv/bin/sam" ]]; then
  export PATH="${LABS_ROOT}/.venv/bin:${PATH}"
fi
if [[ -x "${LABS_ROOT}/.venv/bin/python" ]]; then
  export PATH="${LABS_ROOT}/.venv/bin:${PATH}"
fi

export AWS_REGION="${AWS_REGION:-us-east-1}"
export PROJECT_PREFIX="${PROJECT_PREFIX:-ba-la8s-ai}"
export STACK_NAME="${STACK_NAME:-${PROJECT_PREFIX}-course-labs}"
export BEDROCK_MODEL_ID="${BEDROCK_MODEL_ID:-amazon.nova-lite-v1:0}"
export STACK_ENV_FILE="${STACK_ENV_FILE:-${LABS_ROOT}/.stack.env}"

stack_exists() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --query "Stacks[0].StackStatus" \
    --output text 2>/dev/null
}

stack_is_active() {
  local status
  status="$(stack_exists)" || return 1
  [[ "$status" == "CREATE_COMPLETE" || "$status" == "UPDATE_COMPLETE" ]]
}

write_stack_env() {
  local api_url sm_arn audit_table capstone_sm capstone_approval_sm capstone_fn capstone_approvals
  api_url="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text)"
  sm_arn="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='StateMachineArn'].OutputValue" --output text)"
  audit_table="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='AuditTableName'].OutputValue" --output text)"
  capstone_sm="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='CapstoneIncidentStateMachineArn'].OutputValue" --output text 2>/dev/null || true)"
  capstone_approval_sm="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='CapstoneApprovalStateMachineArn'].OutputValue" --output text 2>/dev/null || true)"
  capstone_fn="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='CapstoneFunctionName'].OutputValue" --output text 2>/dev/null || true)"
  capstone_approvals="$(aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='CapstoneApprovalsTableName'].OutputValue" --output text 2>/dev/null || true)"

  cat >"$STACK_ENV_FILE" <<EOF
# Auto-generated by scripts/start.sh — do not commit
export AWS_REGION=${AWS_REGION}
export PROJECT_PREFIX=${PROJECT_PREFIX}
export STACK_NAME=${STACK_NAME}
export API_ENDPOINT=${api_url}
export STATE_MACHINE_ARN=${sm_arn}
export AUDIT_TABLE_NAME=${audit_table}
export WEEK2_FUNCTION=${PROJECT_PREFIX}-week2-invoke
export AGENT_FUNCTION=${PROJECT_PREFIX}-agent
export BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
export CAPSTONE_INCIDENT_SM_ARN=${capstone_sm}
export CAPSTONE_APPROVAL_SM_ARN=${capstone_approval_sm}
export CAPSTONE_FUNCTION=${capstone_fn}
export CAPSTONE_APPROVALS_TABLE=${capstone_approvals}
EOF
  # shellcheck source=/dev/null
  source "$STACK_ENV_FILE"
}

require_aws_cli() {
  if ! command -v aws &>/dev/null; then
    echo "ERROR: AWS CLI not found."
    exit 1
  fi
  aws sts get-caller-identity --region "$AWS_REGION" >/dev/null
}

require_sam_cli() {
  if ! command -v sam &>/dev/null; then
    echo "ERROR: AWS SAM CLI not found."
    echo "https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html"
    exit 1
  fi
}
