apiVersion: v1
kind: Secret
metadata:
  name: baypay-db
  namespace: baypay-prod
  labels:
    app: payment-service
type: Opaque
stringData:
  BAYPAY_DB_USER: baypay_app
  BAYPAY_DB_PASSWORD: ${BAYPAY_DB_PASSWORD}
---
apiVersion: v1
kind: Secret
metadata:
  name: payment-tls
  namespace: baypay-prod
  labels:
    app: payment-service
type: kubernetes.io/tls
stringData:
  tls.crt: ${PAYMENT_TLS_CERT_PEM}
  tls.key: ${PAYMENT_TLS_KEY_PEM}
