#!/usr/bin/env bash
# Create or update the S3 + CloudFront stack for the documentation portal.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STACK_NAME="${AWS_STACK_NAME:-principal-architect-ks-prod}"
AWS_REGION="${AWS_REGION:-us-west-2}"
PROJECT_NAME="${PROJECT_NAME:-principal-architect-ks}"
ENVIRONMENT="${ENVIRONMENT:-prod}"
TEMPLATE="$ROOT/infrastructure/cloudfront-static-site.yaml"
ENV_FILE="$ROOT/deploy/aws.env"

if ! command -v aws >/dev/null 2>&1; then
  echo "Error: AWS CLI is required. Install: https://aws.amazon.com/cli/" >&2
  exit 1
fi

echo "==> Deploying CloudFormation stack: $STACK_NAME (region: $AWS_REGION)"

PARAM_OVERRIDES=(
  "ProjectName=$PROJECT_NAME"
  "Environment=$ENVIRONMENT"
)

if [[ -n "${CUSTOM_DOMAIN:-}" && -n "${ACM_CERTIFICATE_ARN:-}" ]]; then
  PARAM_OVERRIDES+=(
    "CustomDomainName=$CUSTOM_DOMAIN"
    "AcmCertificateArn=$ACM_CERTIFICATE_ARN"
    "Route53HostedZoneId=${ROUTE53_HOSTED_ZONE_ID:-}"
  )
fi

aws cloudformation deploy \
  --stack-name "$STACK_NAME" \
  --template-file "$TEMPLATE" \
  --parameter-overrides "${PARAM_OVERRIDES[@]}" \
  --capabilities CAPABILITY_IAM \
  --region "$AWS_REGION" \
  --no-fail-on-empty-changeset

echo "==> Waiting for CloudFront distribution to be ready (may take 5–15 minutes)..."
aws cloudformation wait stack-create-complete \
  --stack-name "$STACK_NAME" \
  --region "$AWS_REGION" 2>/dev/null \
  || aws cloudformation wait stack-update-complete \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION"

get_output() {
  aws cloudformation describe-stacks \
    --stack-name "$STACK_NAME" \
    --region "$AWS_REGION" \
    --query "Stacks[0].Outputs[?OutputKey=='$1'].OutputValue" \
    --output text
}

S3_BUCKET="$(get_output BucketName)"
CLOUDFRONT_DISTRIBUTION_ID="$(get_output DistributionId)"
SITE_URL="$(get_output WebsiteURL)"
CLOUDFRONT_URL="$(get_output CloudFrontURL)"

mkdir -p "$ROOT/deploy"
{
  echo "# Auto-generated by scripts/setup-aws-infrastructure.sh — do not commit"
  echo "AWS_REGION=$AWS_REGION"
  echo "AWS_STACK_NAME=$STACK_NAME"
  echo "S3_BUCKET=$S3_BUCKET"
  echo "CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID"
  echo "SITE_URL=$SITE_URL"
  echo "CLOUDFRONT_URL=$CLOUDFRONT_URL"
  [[ -n "${CUSTOM_DOMAIN:-}" ]] && echo "CUSTOM_DOMAIN=$CUSTOM_DOMAIN"
  [[ -n "${ACM_CERTIFICATE_ARN:-}" ]] && echo "ACM_CERTIFICATE_ARN=$ACM_CERTIFICATE_ARN"
} > "$ENV_FILE"

echo ""
echo "=========================================="
echo "  AWS infrastructure ready"
echo "=========================================="
echo "  Portal URL:  $SITE_URL"
echo "  S3 bucket:   $S3_BUCKET"
echo "  CloudFront:  $CLOUDFRONT_DISTRIBUTION_ID"
echo "  Config:      deploy/aws.env"
echo ""
echo "Next: make aws-deploy"
echo "Share $SITE_URL with students."
echo "=========================================="
