#!/usr/bin/env python3
"""Modules 6–7 lesson records (files + large files)."""

from __future__ import annotations

def L(id, title, module, objectives, scenario, why, when, when_not, how_pattern, how_aws, decision, **kw):
    d = dict(
        id=id, title=title, module=module, objectives=objectives, scenario=scenario,
        why=why, when=when, when_not=when_not, how_pattern=how_pattern, how_aws=how_aws,
        decision=decision,
    )
    d.update(kw)
    return d

M06_MOD = "06 — Enterprise File Transfer"

def m06(i, title, scenario, why, when, when_not, how_pattern, how_aws, decision, **kw):
    return L(f"6.{i}", title, M06_MOD, kw.pop("objectives"), scenario, why, when, when_not, how_pattern, how_aws, decision, **kw)

M06 = [
    m06(1, "Why Enterprises Still Use Files",
        "Atlas’s largest supplier still drops a 4 GB CSV at 02:00. They have no API roadmap this decade. Refusing files is refusing to manufacture.",
        "Files persist because they match **batch economics**, **partner capability**, **regulatory extracts**, and **legacy systems**. A file is a bounded snapshot with a name, a checksum, and a business date. Many industries (banking settlements, healthcare claims, retail EDI) standardized on files before REST existed. Cloud does not erase counterparties.",
        ["Partner cannot or will not call your API.", "Bulk is the natural grain.", "Legal evidence is a file artifact.", "Mainframe extract windows."],
        ["Low-latency single-record UX.", "Unknown many consumers of a tiny fact (events).", "Using files to avoid designing an API you actually need internally."],
        "Keep files as a first-class style in the decision framework. Wrap them with a platform (landing, validate, event FileReceived) rather than a unique script per partner. Internally you may translate files into events/commands; at the edge the file remains.",
        "S3 as landing zone; Transfer Family for SFTP; EventBridge on object created. The AWS mapping does not make the partner modern—it makes you operable.",
        "A board member asks “why not APIs for everyone?” Answer in business terms, not protocol nostalgia.",
        objectives=["Argue for files as a valid enterprise style.", "Separate edge protocol from internal processing.", "List industries where files remain the contract."],
        diagram="flowchart LR\n  P[Partner] -->|SFTP file| L[Landing zone]\n  L --> V[Validate]\n  V --> E[FileReceived event]\n  E --> I[Internal APIs / queues]",
        tradeoffs=[("Files", "Partner reach, bulk, evidence", "Latency, hygiene, duplicates"),
                   ("Force API", "Modern internal estate", "Lost revenue if partners cannot comply")],
        checks=[{"q": "Does using S3 mean you no longer “use files”?", "a": "No. S3 objects are files. You modernized the store and automation, not necessarily the partner contract."}],
        anti_patterns=["Shame-driven architecture (“files are legacy so we will not design them”)."],
        architect_note="Capstone 1 and 4 are unwinnable if you pretend files do not exist."),
    m06(2, "Batch Integration",
        "Northbridge posts interest in a nightly batch. Intraday APIs still exist for balances. Both are correct at different grains.",
        "Batch is an integration rhythm: accumulate, cut a file or job, process, reconcile. It optimizes for throughput and simplicity of recovery (rerun the file) at the cost of latency. Mixed estates use batch at the edge and events inside the day.",
        ["End-of-day, payroll, clearing, analytics extracts.", "When reconciliation of a set is the business event."],
        ["When the customer is waiting at a spinner for the batch.", "When a 24h delay violates a 300 ms NFR."],
        "Define the business date, cutoff, SLA to finish, and rerun policy. Idempotent batch jobs. Do not overlap two business dates without a design. Publish BatchCompleted as an event for downstreams.",
        "S3 + EventBridge schedule or Transfer arrival; Step Functions for the job; Glue if it is data-platform heavy (not this course’s center). Keep operational batches in Step Functions + Lambda unless volume demands otherwise.",
        "Can an intraday API and a nightly file share a ledger without double posting? What key prevents it?",
        objectives=["Define batch as a rhythm with cutoff and rerun.", "Combine batch edge with evented internals.", "State reconciliation as part of the batch contract."],
        diagram="flowchart TB\n  Cut[Cutoff 02:00] --> File[Extract/receive file]\n  File --> Job[Batch job]\n  Job --> Rec[Reconcile]\n  Rec --> Ev[BatchCompleted]",
        tradeoffs=[("Batch", "Simple recovery, high throughput", "Latency and cutoff politics")],
        checks=[{"q": "What is a cutoff?", "a": "The business clock time after which records belong to the next file/date."}],
        anti_patterns=["No cutoff, files arrive all day with the same name.", "Rerun that double-posts."],
        architect_note="Always name the business date in the file contract."),
    m06(3, "SFTP",
        "A hospital’s LIS can only push via SFTP with a password they refuse to rotate. You still have to land labs. SFTP is a constraint, not a preference.",
        "SFTP (SSH File Transfer Protocol) is the dominant partner file protocol. It provides encrypted-in-transit transfer, user isolation, and operational familiarity. It does not provide a business workflow, schema validation, or exactly-once processing. Those are your platform’s job once the bytes land.",
        ["Partners mandate SFTP.", "You need a pull or push file path across enterprises."],
        ["Internal microservice hops (use APIs/events).", "Unencrypted FTP in 2026 without a documented waiver and compensating controls."],
        "Standardize user provisioning, key (not password) auth, chrooted directories, IP allow lists, and banner/legal. Separate inbound and outbound trees. Never share one user across two partners.",
        "AWS Transfer Family provides managed SFTP in front of S3. You still design IAM scopes so partner A cannot list partner B. Lab 6 uses this edge.",
        "Password vs SSH key: which belongs in Secrets Manager/KMS and which belongs in a human process?",
        objectives=["Position SFTP as an edge protocol.", "List baseline security controls.", "Separate protocol from processing."],
        diagram="flowchart LR\n  Client[SFTP client] -->|SSH| SFTP[SFTP server]\n  SFTP --> Store[Object storage prefix]",
        tradeoffs=[("SFTP", "Universal partner skill", "User lifecycle and always-on endpoint cost")],
        checks=[{"q": "Does SFTP validate a CSV schema?", "a": "No. It moves bytes. Validation is a downstream platform concern."}],
        anti_patterns=["Shared SFTP user “partners”.", "Landing in a Windows share with no checksum."],
        architect_note="SFTP success is “object exists with integrity,” not “business posting succeeded.”"),
    m06(4, "Managed File Transfer",
        "Harbor’s MFT appliance is out of support. The desire is self-serve partner onboarding, audit, and automation—not another box.",
        "Managed File Transfer (MFT) is a product category: protocol endpoints, partner identities, scheduling, non-repudiation, ops UI. Cloud MFT should keep those controls and add landing-zone automation. If you only stand up SFTP you have a server, not MFT.",
        ["Many partners, audits, SLAs, dual-run with legacy MFT.", "When business users must see file status without SSH."],
        ["A single file from one team this quarter—maybe a secured bucket is enough, with an expiry date."],
        "Capabilities: identity, protocol, routing, encryption, checksums, notifications, audit, self-serve catalog. Map each to platform components. Do not buy an appliance to hide a missing operating model.",
        "Transfer Family + S3 + EventBridge + Step Functions + DynamoDB catalog + Cognito portal is a cloud MFT pattern (see BayLearn file-transfer course). This course treats it as one style among six.",
        "Which MFT capabilities are “protocol” vs “integration platform” vs “portal”?",
        objectives=["Define MFT beyond SFTP.", "List capabilities an architect must cover.", "Avoid appliance-shaped thinking in cloud."],
        diagram="flowchart TB\n  Part[Partners] --> Edge[Protocol edge]\n  Edge --> Land[Landing / audit]\n  Land --> Auto[Automation]\n  Auto --> Ops[Status portal]",
        tradeoffs=[("Full MFT platform", "Ops and audit", "Build cost"),
                   ("Bare SFTP", "Fast", "Scripts and heroics")],
        checks=[{"q": "Name three MFT capabilities SFTP alone does not give you.", "a": "Schema validation, business routing, SLA dashboards (among others)."}],
        anti_patterns=["Lift-and-shift the appliance VM and calling it modernization."],
        architect_note="If nobody can answer “did the file arrive?” without SSH, you do not have MFT."),
    m06(5, "AWS Transfer Family",
        "Lab 6’s edge. You must know what you are paying for by the hour.",
        "Transfer Family is a managed protocol endpoint (SFTP/FTPS/FTP/AS2) that stores objects in S3 or EFS. It is the AWS implementation of the SFTP edge—not the whole architecture. Cost is dominated by the **online endpoint hours**, so labs must stop or destroy it.",
        ["You need managed SFTP without babysitting an EC2 OpenSSH box.", "You want IAM-mapped access to prefixes."],
        ["High-volume internal copies that never leave AWS (use S3 APIs).", "As a place to run business logic."],
        "Design: per-partner users, scoped IAM home directories, encryption, logging to CloudWatch, no public exposure beyond need, keys not passwords. Workflows can trigger on upload but still keep business logic in your processors.",
        "AWS Transfer Family server, service-managed users or IdP, S3 backend, optional connectors for outbound. Lab 6 Terraform enables a server you must destroy. Estimated cost is in the lab workbook.",
        "Why is leaving Transfer Family running over a weekend a cost incident rather than a convenience?",
        objectives=["Map Transfer Family to the SFTP edge pattern.", "State cost and security controls.", "Refuse to put domain logic in the protocol service."],
        diagram="flowchart LR\n  U[Partner user] --> TF[Transfer Family]\n  TF --> IAM[Scoped role]\n  IAM --> S3[(S3 prefix)]",
        tradeoffs=[("Managed SFTP", "Less patching", "Hourly cost while ONLINE")],
        checks=[{"q": "What is the primary ongoing cost driver?", "a": "The Transfer Family server endpoint hours while ONLINE."}],
        anti_patterns=["One IAM role that can read the entire bucket.", "FTP enabled “for testing” in prod."],
        architect_note="Cleanup is part of the architecture. Cost is an NFR."),
    m06(6, "Amazon S3",
        "S3 is the system of record for landed files, not a random folder.",
        "Object storage gives durability, versioning, lifecycle, encryption, eventing, and prefix isolation. Treat prefixes as **contracts**: inbound, quarantine, accepted, archive. Bucket design is security design (partner isolation).",
        ["Landing, staging, archive, large payloads, claim-check.", "Any file style on AWS."],
        ["As a database for single-row queries.", "As a queue (it is not exactly-once work orchestration)."],
        "Versioning on. Block public access. KMS. Separate buckets or strong prefixes per class of data. Events on ObjectCreated for automation. Lifecycle to cheaper storage after the operational window. Object Lock if legal hold requires it.",
        "S3 + EventBridge notifications (or S3 fan-out). Bucket keys for KMS cost. Lab 6 uses inbound/quarantine/archive prefixes.",
        "Partner A and B share a bucket. What IAM condition prevents A from reading B, and what prefix standard do you need?",
        objectives=["Use S3 as a landing-zone system of record.", "Design prefixes as contracts.", "Enable versioning and events."],
        diagram="flowchart TB\n  In[inbound/] --> Q[quarantine/]\n  Q --> Ok[accepted/]\n  Ok --> Ar[archive/]",
        tradeoffs=[("Shared bucket + prefixes", "Fewer buckets", "IAM complexity"),
                   ("Bucket per partner", "Hard isolation", "Quota and ops sprawl")],
        checks=[{"q": "Why versioning?", "a": "So overwrite or delete does not destroy evidence; reprocessing can use a specific version ID."}],
        anti_patterns=["Public ACL “just for a test file.”", "Same prefix for inbound and archive."],
        architect_note="If you cannot point to the object version of a payment file, you cannot survive an audit."),
    m06(7, "Large Files",
        "A 12 GB image package will not pass API Gateway or SQS. Claim-check exists because physics exists.",
        "Large files stress timeouts, memory, cost, and virus scanning. They must land via multipart/SFTP/S3 APIs, then be processed by workers sized for the job (Lambda has size and time limits; Fargate/ECS may be required). Never put the bytes on the bus.",
        ["Hundreds of MB to tens of GB+.", "Media, CAD, genomic, full-book extracts."],
        ["Hiding a 50 GB payload inside a “message.”", "Streaming the whole file through a 512 MB Lambda without a plan."],
        "Claim-check: message/event holds URI + checksum + size. Workers stream, do not buffer entirely if avoidable. Multipart upload. Checkpoints. Module 7 goes deep; here you learn to refuse the wrong style.",
        "S3 multipart, Transfer Family, ECS for heavy CPU hashing if needed, Lambda for lightweight metadata. Lab 7 implements the API-init + direct S3 path.",
        "Which of API Gateway, SQS, DynamoDB item, EventBridge put-events is acceptable as the primary transport for 25 GB?",
        objectives=["Refuse illegal transports for large payloads.", "Introduce claim-check.", "Size workers to file reality."],
        diagram="flowchart LR\n  F[50GB object] --> S3[(S3)]\n  S3 --> Ev[FileReceived pointer]\n  Ev --> W[Worker streams object]",
        tradeoffs=[("Direct-to-S3", "Physics-friendly", "More client complexity"),
                   ("Proxy through API", "Simple client", "Hard limits and cost")],
        checks=[{"q": "What travels on the event bus for a large file?", "a": "A pointer (bucket, key, version, checksum), not the bytes."}],
        anti_patterns=["Base64 in JSON on SQS.", "Single PUT from a browser to API Gateway."],
        architect_note="The 25 GB challenge in Module 14 is this lesson as a multiple-choice trap."),
    m06(8, "File Naming Standards",
        "Two partners both send orders.csv every day. One overwrites the other. Naming is an interface.",
        "Names encode partner, date, sequence, type, and uniqueness. They enable routing, idempotency, and human ops. Unnamed “data.csv” is an incident. Include business date and a unique ID. Forbid spaces and PII in names.",
        ["Any inbound/outbound file contract.", "When humans and machines both need to find a file."],
        ["Encoding PANs or names of patients in the filename.", "Relying on last-modified time as the only identity."],
        "Pattern example: inbound/{partner}/{yyyy-mm-dd}/{type}_{seq}_{uuid}.csv. Document it. Reject non-conforming names into quarantine. Do not trust client clocks for business date if the contract says otherwise—sometimes the name is the date.",
        "S3 keys are the name. Lambda validator enforces the regex. Event metadata copies parsed fields so routing does not regex forever.",
        "If uuid is missing but seq is present, can you still detect duplicates across a daylight-saving rerun?",
        objectives=["Treat filenames as contracts.", "Include partner, date, type, uniqueness.", "Quarantine noncompliant names."],
        diagram="flowchart TB\n  N[Name parse] --> Ok{Match standard?}\n  Ok -->|yes| Land[Accept path]\n  Ok -->|no| Q[Quarantine]",
        tradeoffs=[("Rich names", "Self-describing", "Partners must implement"),
                   ("Opaque UUIDs only", "Easy unique", "Humans cannot ops")],
        checks=[{"q": "Why not put account numbers in filenames?", "a": "They leak in logs, tickets, and listings. Identifiers in the name should be non-sensitive."}],
        anti_patterns=["orders.csv every day in the same key.", "Windows-incompatible characters “because Unix is fine.”"],
        architect_note="Write the regex in the partner onboarding pack."),
    m06(9, "Metadata",
        "Checksum, partner ID, size, and correlation ID lived only in an email. The email was deleted. Metadata must travel with the object.",
        "Metadata is the file’s envelope: who, when, what schema version, checksum, correlation, sensitivity. Store it in object metadata and in an operational table. Events should copy a subset. Without metadata you cannot duplicate-detect or audit.",
        ["Every landed file.", "Cross-system tracing from SFTP user to posting."],
        ["Storing the entire CSV as “metadata.”", "Sensitive data in unencrypted user-defined metadata that lands in logs."],
        "On land: capture Transfer user, source IP (if available), size, etag/checksum, parsed name fields. Write a DynamoDB item FileId → metadata. Emit FileReceived with pointers. This is what the AI ops agent will query in Module 15.",
        "S3 user-metadata (size limits), DynamoDB catalog, EventBridge detail. Lab 6 writes a catalog item.",
        "Which metadata must be queryable by “did partner ABC send today’s settlement?” without listing the entire bucket?",
        objectives=["Define the file envelope.", "Persist a catalog, not only S3 listings.", "Feed observability and agents."],
        diagram="flowchart LR\n  Obj[S3 object] --> Cat[(File catalog)]\n  Cat --> Ev[FileReceived]\n  Cat --> Ag[Ops agent tools]",
        tradeoffs=[("Catalog table", "Queryable ops", "Must stay in sync with S3"),
                   ("S3 inventory only", "Cheap", "Slow, awkward queries")],
        checks=[{"q": "Why not rely on S3 list as the catalog?", "a": "List is not a business query API, is slower, and lacks partner/SLA fields you need."}],
        anti_patterns=["Metadata only in Slack.", "No correlation ID on file events."],
        architect_note="The banking ops agent is a metadata consumer. Design the table for those questions."),
    m06(10, "File Validation",
        "A CSV with the right name contained HTML. The processor crashed in production. Validation is a gate, not a courtesy.",
        "Validation: antivirus/malware where required, format, schema, row counts, referential checks, and business thresholds. Fail to quarantine with reasons. Do not partially post a payment file without a defined policy (all-or-nothing vs partial with report).",
        ["Every inbound file from outside a trust boundary.", "After internal extracts too if you do not trust the producer."],
        ["Validating only in Excel after posting.", "Letting a 50 GB file fully load into memory to “validate.”"],
        "Layer: (1) size/name/MIME, (2) integrity checksum, (3) schema sample or full parse streaming, (4) business rules. Emit FileQuarantined vs FileAccepted. Human or partner notification.",
        "Lambda streaming CSV (careful with size—use chunking or ECS). ClamAV patterns on ECS if malware scanning is in scope. Lab 6 implements schema + duplicate + checksum gates.",
        "All-or-nothing vs partial accept: which does a payment file typically need, and why?",
        objectives=["Layer validation from cheap to expensive.", "Define quarantine outcomes.", "Choose all-or-nothing vs partial."],
        diagram="flowchart TB\n  F[File] --> G1[Name/size]\n  G1 --> G2[Checksum]\n  G2 --> G3[Schema]\n  G3 --> G4[Business]\n  G4 --> A[Accepted] \n  G1 --> Q[Quarantine]\n  G2 --> Q\n  G3 --> Q\n  G4 --> Q",
        tradeoffs=[("All-or-nothing", "Cleaner ledger", "One bad row delays all"),
                   ("Partial", "Progress", "Harder reconciliation")],
        checks=[{"q": "Where do invalid files go?", "a": "Quarantine prefix + catalog status + notification—not silent delete."}],
        anti_patterns=["Deleting invalid files to keep buckets pretty.", "Full in-memory parse of huge files."],
        architect_note="Quarantine is a product: partners need a reason code."),
    m06(11, "Checksums",
        "A truncated SFTP transfer posted as a complete payroll. Checksums are not optional in money files.",
        "Checksums (SHA-256 typically) prove integrity. Partners may send a sidecar .sha256 or a manifest. You compute on land and compare. ETags are not a cryptographic checksum (especially multipart). Record algorithm + value in the catalog.",
        ["Any file where truncation or tamper matters.", "Legal/regulatory transfers."],
        ["Using Content-Length alone.", "MD5 as the only control in a high-threat model if you can do better."],
        "Contract: algorithm, sidecar or header, who computes. Worker streams hash. Mismatch → quarantine. Store checksum for duplicate detection too (same bytes twice).",
        "Lambda/ECS compute hash; S3 checksum algorithms on upload when clients support them. Lab 6 compares sidecar vs computed.",
        "Partner cannot send a sidecar. What compensating control do you require?",
        objectives=["Use strong checksums as integrity evidence.", "Do not confuse ETag with SHA-256.", "Bind checksums to the catalog."],
        diagram="flowchart LR\n  F[File] --> H[Compute SHA-256]\n  S[Sidecar] --> C{Match}\n  H --> C\n  C -->|no| Q[Quarantine]\n  C -->|yes| A[Accept]",
        tradeoffs=[("Sidecar", "Independent evidence", "Partner capability"),
                   ("Platform-only hash", "Always available", "Does not detect partner-side truncation before send as well")],
        checks=[{"q": "Why is multipart ETag a poor integrity proof?", "a": "It is not a simple MD5 of the whole object; it is not a cryptographic signature of contents."}],
        anti_patterns=["Checksum in the filename only.", "Skipping hash on “small” payment files."],
        architect_note="Integrity is a security and a business control. Put it in the ADR."),
    m06(12, "Encryption",
        "A claims file at rest in an unencrypted bucket with a public-ish ACL is a reportable event waiting to happen.",
        "Encrypt in transit (SFTP/TLS) and at rest (KMS). Manage keys per classification. Restrict who can decrypt. Do not email passwords for zip files as your enterprise encryption strategy. Partner-side PGP still exists; treat it as an adapter.",
        ["All sensitive files.", "Cross-account sharing with separate KMS policies."],
        ["Double encryption theater without key management.", "Client-side crypto that loses keys and the business with them—unless you have a designed key story."],
        "Default: TLS + SSE-KMS. Bucket keys. Separate CMKs for PCI vs general. Grants for processors. Rotate. CloudTrail on key use. If PGP is required, decrypt in a tight worker, never store plaintext in inbound.",
        "KMS, S3 encryption, Transfer Family TLS. Secrets Manager for partner credentials. Lab 6 and 12 enforce this.",
        "Who is allowed to kms:Decrypt the healthcare landing CMK, and why is that not the same as s3:GetObject on every bucket?",
        objectives=["Mandate transit and rest encryption.", "Use KMS as the control plane for file class.", "Treat PGP as an adapter, not a platform."],
        diagram="flowchart LR\n  P[Partner TLS/SFTP] --> S3\n  S3 -->|SSE-KMS| KMS[CMK]\n  Proc[Processor role] --> KMS",
        tradeoffs=[("CMK per class", "Blast radius", "Key sprawl"),
                   ("One CMK", "Simple", "Over-broad decrypt")],
        checks=[{"q": "Does HTTPS to a bucket make at-rest encryption unnecessary?", "a": "No. Transit and rest are different threats (path vs stolen disk/backup/mis-list)."}],
        anti_patterns=["SSE-S3 only when a regulator asked for customer-managed keys.", "Plain FTP “internal only.”"],
        architect_note="Encryption without IAM is incomplete. IAM without encryption is incomplete."),
    m06(13, "Duplicate Detection",
        "The partner retried an SFTP PUT after a timeout. You posted payroll twice. Duplicates are the file equivalent of missing idempotency keys.",
        "Duplicates arrive because of retries, overlapping schedules, or copied files. Detect by checksum, by business natural key (file id in header), and by name. Policy: reject duplicate, or ignore if already posted, never double-post. Store seen hashes/IDs with TTL longer than the retry window (days to years in finance).",
        ["Every inbound payment, payroll, claims, settlement file.", "Any partner known to retry."],
        ["Using only filename when names are reused daily.", "Hash-only when two legal files can be identical (rare but know it)."],
        "Catalog unique constraint on (partner, businessDate, fileId) and/or checksum. First writer wins. Second gets DuplicateDetected event and partner notification. Replay of a failed file is not a duplicate if the first never posted—status matters.",
        "DynamoDB conditional put. Lab 6 implements this. Chaos lab will drop a duplicate on purpose.",
        "File failed validation then is resent identically. Duplicate or reprocess? What status on the first record makes this safe?",
        objectives=["Treat duplicate files as a first-class case.", "Key on business identity + checksum.", "Never double-post."],
        diagram="flowchart TB\n  In[Inbound] --> D{Seen ID or hash?}\n  D -->|yes posted| Dup[Reject duplicate]\n  D -->|yes failed| Rep[Reprocess policy]\n  D -->|no| Val[Validate]",
        tradeoffs=[("Strict hash dedupe", "Stops retries", "Blocks legitimate identical extracts if that can happen"),
                   ("Business fileId", "Intent-based", "Partner must send IDs")],
        checks=[{"q": "Is a retry after a quarantine a duplicate?", "a": "Only if the original was successfully posted. Failed files need a defined reprocess path."}],
        anti_patterns=["Overwrite same S3 key and hoping versioning saves the ops story without a catalog."],
        architect_note="This is Lesson 2.11 for bytes. Same idea, different grain."),
    m06(14, "File Processing",
        "Accepted files still need posting, not just storage. Processing is a workflow with checkpoints.",
        "Processing transforms a valid file into business effects: rows to commands, aggregates to ledgers. Use streaming/chunking, checkpoint row numbers, and idempotent row keys. Prefer emitting per-row commands to a queue if downstream is TPS-limited (back-pressure).",
        ["After accept.", "When mapping to domain APIs or ledgers."],
        ["Giant in-memory pandas on Lambda for 20 GB.", "Calling a sync API per row without rate limits."],
        "Step Functions or ECS job: read, chunk, send messages, wait, summarize, reconcile. Checkpoint in DynamoDB. Poison rows to a sidecar error file. Complete with FileProcessed event and metrics (rows ok/fail).",
        "Step Functions + Lambda or Fargate. SQS between parse and post. Lab 6 uses a simplified Lambda processor; capstones should show checkpoints.",
        "10 million rows at 50 TPS downstream: do you need a queue, and what is the wall-clock?",
        objectives=["Process with checkpoints and row idempotency.", "Apply back-pressure to downstream APIs.", "Emit completion facts."],
        diagram="flowchart LR\n  Acc[Accepted file] --> Chunk[Chunker]\n  Chunk --> Q[Row command queue]\n  Q --> Post[Poster]\n  Post --> Rec[Reconcile]",
        tradeoffs=[("Row commands", "Retry granularity", "More messages"),
                   ("Monolithic job", "Simple", "Fail-all or complex resume")],
        checks=[{"q": "What is a checkpoint?", "a": "Durable progress (byte or row) so a crash does not restart from zero or double-post."}],
        anti_patterns=["No row identity.", "Processor with dynamodb:* and admin S3."],
        architect_note="Processing is where file style meets message style. Composition is normal."),
    m06(15, "File Routing",
        "Payments files must not enter the marketing bucket. Routing is content + partner + type, with security.",
        "Routing decides the processing pipeline: partner, file type, country, sensitivity. Implement as a table, not as twenty undocumented if-statements. Wrong routing is a data-leak incident.",
        ["Multi-partner landing zones.", "Multiple downstream products."],
        ["Routing on payload PII in logs.", "Hard-coded partner names in Lambda without a table."],
        "Config: partner + type → pipeline, schema, destination, pageable owners. Unknown combination → quarantine, not a default “misc” processor that posts money.",
        "DynamoDB routing table, EventBridge rules on metadata, Step Functions choice. Lab 6 uses a small map in config; capstones need a table.",
        "A new partner is onboarded. Should that require a code deploy? What would a self-serve MFT do instead?",
        objectives=["Route from metadata, not folklore.", "Fail unknown routes to quarantine.", "Keep routing data-driven."],
        diagram="flowchart TB\n  Meta[Partner+type] --> RT[(Routing table)]\n  RT --> P1[Pipeline A]\n  RT --> P2[Pipeline B]\n  RT --> Q[Quarantine unknown]",
        tradeoffs=[("Table-driven", "Onboard without deploys", "Need governance of the table"),
                   ("Code-if", "Obvious in git", "Every partner is a release")],
        checks=[{"q": "What should happen to an unknown partner/type pair?", "a": "Quarantine and alert—not a default poster."}],
        anti_patterns=["Default route to production ledger.", "Routing rules only in someone’s head."],
        architect_note="Self-serve onboarding is a routing-table product plus identity, not a new Lambda per partner."),
    m06(16, "File Acknowledgements",
        "Partners ask “did you get it?” If the only answer is a help desk ticket, you designed a call center, not a platform.",
        "Acknowledgements (MDN, .ack files, webhooks, status APIs) close the loop. They are a contract: received, accepted, rejected, posted. They should include correlation IDs and reason codes. Do not ack “posted” at SFTP RECEIVE time.",
        ["Any SLA with a partner.", "When finance reconciles against your receipt."],
        ["Ack success at protocol receive before validation.", "Ack via an unsigned email from a personal inbox."],
        "States: Received → Validated → Posted / Rejected. Emit each as event and as partner-visible status. Optional outbound ACK file on SFTP. Status API for portals and agents (Module 15).",
        "DynamoDB status, SNS to partner webhook, outbound Transfer connector or S3 drop. Lab 6 notifies via SNS email/SMS-less email placeholder and catalog status.",
        "At which state would you tell a bank “safe to consider it received for SLA” vs “safe to consider it settled”?",
        objectives=["Separate received vs posted acks.", "Offer machine-readable status.", "Avoid premature success."],
        diagram="stateDiagram-v2\n  [*] --> Received\n  Received --> Validated\n  Received --> Rejected\n  Validated --> Posted\n  Validated --> Rejected\n  Posted --> [*]\n  Rejected --> [*]",
        tradeoffs=[("Rich ACK", "Fewer tickets", "Must keep status honest"),
                   ("No ACK", "Less work", "Operational noise")],
        checks=[{"q": "Why not ack posted at SFTP success?", "a": "Bytes landed, but validation and ledger posting have not occurred. You would lie."}],
        anti_patterns=["Always-200 webhook.", "ACK file that overwrites and loses history."],
        architect_note="The ops agent’s “did it arrive?” is this catalog. Build it now."),
    m06(17, "File Reprocessing",
        "A schema bug rejected a good file. After the fix, reprocessing must be authorized, auditable, and idempotent.",
        "Reprocess is a controlled write: copy from archive/quarantine, new correlation ID linked to original, same duplicate rules against *posted* outcomes. It is a favorite agent action—and therefore must be HITL in Module 15. Not every user may reprocess payments.",
        ["After a platform bug.", "After a partner resent is not possible."],
        ["Unattended infinite reprocess loops.", "Reprocess that bypasses validation “because we know it is fine.”"],
        "Runbook: identify file version, reason, approver, new run ID, validate again, post idempotently, audit event FileReprocessed. Store who approved. Capstone 1 requires this.",
        "Step Functions with an approval task (or a DynamoDB approval record the agent writes). IAM so only a role can start reprocess. Lab 6 includes a replay path analogous to SQS DLQ replay.",
        "Should a customer-support agent be able to reprocess a 20 GB settlement without a second approver?",
        objectives=["Make reprocess auditable and idempotent.", "Require authorization commensurate with risk.", "Link new runs to original files."],
        diagram="flowchart LR\n  Q[Quarantine/archive] --> Appr[Approval]\n  Appr --> Val[Validate again]\n  Val --> Post[Idempotent post]\n  Post --> Aud[Audit event]",
        tradeoffs=[("HITL reprocess", "Safer", "Slower recovery"),
                   ("One-click replay", "Fast", "Easy fraud/mistake")],
        checks=[{"q": "What must not change on reprocess?", "a": "The business identity of the file; duplicate detection against successful posts still applies."}],
        anti_patterns=["Reprocess as a raw S3 copy into inbound with no audit.", "Same correlation ID masking that a second run occurred."],
        architect_note="Write actions for agents start here. Design the approval now."),
    m06(18, "File Archival",
        "A regulator asks for the file from 17 months ago. If lifecycle deleted it, you have a legal problem, not a storage problem.",
        "Archive is a retention design: how long, which storage class, legal hold, who can read, encryption, and retrieval SLA. Operational prefixes should not be your 7-year store. Move posted files to archive with metadata intact. Prove immutability if required (WORM).",
        ["Regulated files.", "Forensic replay needs.", "Cost reduction after the operational window."],
        ["Archive as the only copy while processing is live.", "Infinite retention of everything including malware samples without a policy."],
        "Policy table: data class → retention → storage class → legal hold. Lifecycle rules. Separate account for archives if threat model requires. Test a restore once a quarter.",
        "S3 lifecycle to IA/Glacier, Object Lock where needed, Vault Lock patterns, cross-account. Cost in the ADR. Lab 6 uses a short lifecycle so student accounts do not store forever—**document that production would differ**.",
        "If Glacier restore is 12 hours and the SLA to reprocess is 1 hour, is Glacier the right operational archive?",
        objectives=["Design retention by data class.", "Separate ops store from legal archive.", "Test restore."],
        diagram="flowchart LR\n  Ops[Operational prefix days] --> Arch[Archive years]\n  Arch --> Legal[Legal hold optional]\n  Arch --> Restore[Tested restore path]",
        tradeoffs=[("Cold archive", "Cost", "Retrieval time"),
                   ("Hot forever", "Fast replay", "Cost and exposure")],
        checks=[{"q": "Why not use the lab’s 1-day lifecycle in production?", "a": "Labs optimize cost. Production retention is a legal NFR and belongs in the ADR."}],
        anti_patterns=["Deleting inbound to save cost before archive copy confirms.", "Archive bucket world-readable."],
        architect_note="Retention is an architecture decision with counsel, not a lifecycle checkbox copied from a blog."),
]

M07_MOD = "07 — Large File Architecture"

M07 = [
    L("7.1", "Why Large Payloads Break Synchronous APIs", M07_MOD,
      ["Quantify gateway, proxy, and function limits as NFRs.",
       "Explain memory and timeout physics.",
       "Choose claim-check + async status as the default large-file API."],
      "A client posts 25 GB to API Gateway. It will not work. The architecture was wrong before the first byte.",
      "Synchronous HTTP APIs are built for modest representations. Gateways cap body size and time. Load balancers idle-timeout. Lambdas cap memory and duration. Even if you raised every timeout, holding a multi-GB buffer in a request thread is an expensive way to copy to S3. Large payloads need **out-of-band transfer**.",
      ["Any payload approaching gateway limits (far earlier than 25 GB—think tens of MB as a smell).",
       "Long-running processing after upload."],
      ["Keeping a 50 GB video inside DynamoDB.",
       "SQS as a transport for the bytes."],
      "API issues a short-lived upload location (presigned URL or Transfer instruction), client uploads directly to object storage (multipart), platform emits ObjectCreated, processor works async, client polls/status-subscribes. This is Lab 7.",
      "API Gateway + Lambda for init/status only. S3 multipart. EventBridge on object created. Processing Lambda/ECS. DynamoDB status. Never the bytes through the gateway.",
      "Which of A) API Gateway B) direct object storage C) SQS D) DynamoDB is acceptable for 25 GB, and why are the others physically or economically wrong?",
      diagram="sequenceDiagram\n  participant C as Client\n  participant A as API\n  participant S as S3\n  participant P as Processor\n  C->>A: POST /uploads\n  A-->>C: upload URL + id\n  C->>S: multipart PUT\n  S->>P: ObjectCreated\n  C->>A: GET /uploads/id\n  A-->>C: PROCESSING / DONE",
      tradeoffs=[("Direct upload", "Scales to GB", "Client must speak S3/multipart"),
                 ("Proxied upload", "Simple HTTP POST", "Hard limits")],
      checks=[{"q": "What does the API return on init?", "a": "An upload locator, a file/job ID, and possibly part size hints—not 201 processed."}],
      anti_patterns=["Raising API Gateway limits as the strategy.", "Putting base64 in JSON."],
      architect_note="This is the architecture challenge example in the course spec. Students must explain, not guess."),
    L("7.2", "Presigned Uploads and Claim Check", M07_MOD,
      ["Issue time-boxed, least-privilege upload credentials.",
       "Bind uploads to a job ID and expected checksum.",
       "Treat the object URI as the claim check for later messages."],
      "An open bucket “uploads/” with public write became a malware hotel. Presigning exists to avoid that.",
      "Presigned URLs grant a specific operation on a specific key for a short time. The server chooses the key (job ID). After upload, events carry the claim check: bucket, key, version, size, checksum. Downstream queues never contain bytes.",
      ["Browser and partner HTTPS uploads to S3.",
       "When you do not want Transfer Family for a one-off large object (still may want SFTP for partners)."],
      ["Long-lived presigns (days) with write to *.",
       "Client-chosen keys in a shared prefix without isolation."],
      "Init API authenticates, creates catalog row PENDING, returns presign for PUT/multipart. Complete API or S3 event verifies size/checksum, marks LANDED, starts pipeline. Expire abandoned PENDING.",
      "s3 generate_presigned_url / presigned POST. KMS via bucket encryption. Lab 7 implements init + client upload + event.",
      "If the presign allows PUT to any key, what is the threat?",
      diagram="flowchart LR\n  Init[Init API] --> PS[Presigned PUT]\n  PS --> Obj[Object]\n  Obj --> CC[Claim check event]\n  CC --> Q[Process queue]",
      tradeoffs=[("Presign", "No public bucket", "Clock skew and expiry UX"),
                 ("Transfer Family", "Partner SFTP", "Hourly cost")],
      checks=[{"q": "What is a claim check?", "a": "A reference to a large payload stored elsewhere, carried by messages/events instead of the payload itself."}],
      anti_patterns=["Public-write prefix.", "Presign expiry of one week for a 2-minute upload."],
      architect_note="Least privilege applies to temporary creds too."),
    L("7.3", "Multipart, Streaming, and Worker Choice", M07_MOD,
      ["Use multipart upload for reliability and parallelism.",
       "Stream in workers; watch Lambda size/time.",
       "Escalate to ECS/Fargate when hashing/scanning GB-scale."],
      "A 10 GB file hashed in a 2 GB Lambda OOM-killed forever. Worker choice is an architecture decision.",
      "Multipart allows resume and parallel parts. Processors should stream (hash, scan, parse) with bounded memory. Lambda is excellent for control-plane and modest files; Fargate/ECS/batch for heavy CPU, long time, or huge memory. Do not be heroic.",
      ["Files above a documented threshold (e.g. 500 MB) go to Fargate.",
       "Small files stay on Lambda for cost."],
      ["One Lambda memory setting for all sizes.",
       "Loading entire files into BytesIO “for convenience.”"],
      "Threshold table in the ADR. Step Functions chooses the worker. Checkpoints for parse. Virus scan as a required stage for untrusted sources.",
      "S3 multipart, Lambda vs ECS (see also the file-transfer course Lab 9). Lab 7 can process small files with Lambda and document the threshold; do not pretend 50 GB on Lambda.",
      "At 100 MB, 1 GB, 10 GB, 50 GB: which worker and why?",
      diagram="flowchart TB\n  Size{Size} -->|small| L[Lambda stream]\n  Size -->|large| F[Fargate worker]\n  L --> S[Status]\n  F --> S",
      tradeoffs=[("Lambda", "Cheap, simple", "Hard limits"),
                 ("Fargate", "Power", "VPC/image complexity and cost per run")],
      checks=[{"q": "Why stream the hash?", "a": "To keep memory O(1) relative to file size and to fail fast on truncation."}],
      anti_patterns=["multipart abandoned parts leaking cost.", "No abort of incomplete uploads."],
      architect_note="Incomplete multipart uploads cost money. Lifecycle abort rules are architecture."),
    L("7.4", "Asynchronous Status Patterns", M07_MOD,
      ["Offer GET status, webhooks, and events for completion.",
       "Make status the UX contract for long work.",
       "Never block the init HTTP call on processing."],
      "Mobile uploaded 2 GB and the app froze waiting. Status patterns exist so UX can be honest.",
      "202 Accepted + job resource is the API analog of “message received.” Status values: PENDING_UPLOAD, LANDED, VALIDATING, PROCESSING, COMPLETED, FAILED. Clients poll with backoff or subscribe to events. Webhooks need signing and retries.",
      ["Any work longer than a gateway timeout.",
       "Human-visible long jobs."],
      ["Spin-waiting in the init Lambda until processing ends.",
       "Unverified webhooks to customer URLs."],
      "Status in DynamoDB. GET /uploads/{id}. Event FileProcessed. Optional websocket/SNS. Include percent or stage, error code, correlation ID. Lab 7 requires GET status.",
      "API Gateway GET to Lambda to DynamoDB. EventBridge for push. Same correlation ID as the file catalog.",
      "Poll every 50 ms vs exponential backoff: which harms the platform, and how do you document the client contract?",
      diagram="stateDiagram-v2\n  [*] --> PENDING_UPLOAD\n  PENDING_UPLOAD --> LANDED\n  LANDED --> PROCESSING\n  PROCESSING --> COMPLETED\n  PROCESSING --> FAILED",
      tradeoffs=[("Poll", "Easy clients", "Load if naive"),
                 ("Push events", "Efficient", "Client must subscribe")],
      checks=[{"q": "What HTTP status on init when processing will take minutes?", "a": "202 Accepted (or 201 created of a job resource)—not 200 completed."}],
      anti_patterns=["Status 200 with empty body meaning unknown.", "Job IDs that are sequential and guessable for other tenants."],
      architect_note="Guessable job IDs are an IDOR waiting to happen. Use unguessable IDs plus authz."),
    L("7.5", "Integrity, Malware, and Poison Large Objects", M07_MOD,
      ["Scan untrusted files before they fan out.",
       "Quarantine without blocking the entire landing zone.",
       "Bound resource usage so zip bombs cannot take down workers."],
      "A 200 KB zip expanded to 40 GB in a parser. Large-file architecture includes hostile files, not just honest CAD.",
      "Untrusted bytes: malware scan, archive bomb limits, max rows, max expansion ratio, timeouts. Fail to quarantine. Do not notify twenty systems with a pointer to malware. Security and reliability meet here.",
      ["Any external upload.",
       "Any file that will be opened by internal users."],
      ["Skipping scan “because it is CSV.”",
       "Scanning only after posting to the ledger."],
      "Stage: land to unscanned prefix → scan/hash → promote. Resource limits on workers. Circuit-break a partner who sends bombs. Capstone 3 is strict here.",
      "Separate prefixes, possibly a scanning engine on Fargate, GuardDuty malware protection for S3 where appropriate. Lab 7 at least enforces size and checksum; document scan as required in production ADRs.",
      "Where does the object live while unscanned, and which roles can read it?",
      diagram="flowchart LR\n  U[Upload] --> Un[unscanned/]\n  Un --> Sc[Scan + hash]\n  Sc -->|clean| Cl[clean/]\n  Sc -->|bad| Q[quarantine/]",
      tradeoffs=[("Sync scan before event", "Safer fan-out", "Longer time to first event"),
                 ("Async scan", "Faster ingest", "Risk of premature consume")],
      checks=[{"q": "Should FileReceived fire from the unscanned prefix?", "a": "Generally no for untrusted sources. Fire FileLandedUnscanned internally if needed, FileReceived after promotion."}],
      anti_patterns=["Everyone can read unscanned.", "No max-bytes on parsers."],
      architect_note="Hostile files are a reliability incident and a security incident. Design both."),
    L("7.6", "Cost and Performance at GB Scale", M07_MOD,
      ["Model S3 request, transfer, KMS, and compute cost.",
       "Avoid NAT and cross-AZ chatter for huge copies.",
       "Put cost in the ADR next to latency."],
      "A “simple” cross-region copy of nightly 50 GB × 50 partners became a five-figure bill. Large-file architecture is FinOps.",
      "Cost drivers: storage, PUT parts, GET by workers, KMS per object, Transfer Family hours, NAT if you hairpin, inter-region replication, failed retries that re-read. Performance: parallelism of parts, worker placement, checksum CPU. Architects estimate before they bless the pattern.",
      ["Any design above a few GB/day.",
       "Multi-region DR copies."],
      ["Ignoring KMS request costs on millions of tiny files (different problem) or GB-scale re-hashes every retry."],
      "Estimate: volume × size × GET/PUT counts × region. Cache checksums. Don’t re-download on every consumer—claim-check plus one processor that emits small facts. Lifecycle incomplete uploads.",
      "S3 pricing, Transfer Family, Data Transfer. Lab 7 should stay tiny (sample files). Capstone 4 must include a cost paragraph for 50 partners × 20 GB.",
      "50 partners × 20 GB nightly × 30 days: what is the dominant cost if you also copy to a second region?",
      diagram="flowchart TB\n  In[Ingress] --> S[S3]\n  S --> W[Workers GET]\n  S --> R[Replication]\n  W --> C[KMS]\n  R --> C2[Transfer out]",
      tradeoffs=[("Replicate everything", "DR", "Transfer cost"),
                 ("Reprocess from origin", "Cheaper storage", "RTO risk")],
      checks=[{"q": "Why can retries explode cost at GB scale?", "a": "Each retry may GET the object again and re-burn CPU/KMS. Idempotent checkpoints save money, not only correctness."}],
      anti_patterns=["NAT gateway for S3 from private subnets without a gateway endpoint.", "Three consumers each downloading the 50 GB object."],
      architect_note="Module 14’s 20 GB × 50 orgs challenge is this lesson with a calculator."),
]
