#!/usr/bin/env python3
"""Modules 8–10 lesson records (ESB, modernization, EIP catalog)."""

from __future__ import annotations

def L(id, title, module, objectives, scenario, why, when, when_not, how_pattern, how_aws, decision, **kw):
    d = dict(
        id=id, title=title, module=module, objectives=objectives, scenario=scenario,
        why=why, when=when, when_not=when_not, how_pattern=how_pattern, how_aws=how_aws,
        decision=decision,
    )
    d.update(kw)
    return d

M08_MOD = "08 — ESB and Traditional Enterprise Integration"
M09_MOD = "09 — ESB Modernization"
M10_MOD = "10 — Enterprise Integration Patterns"

M08 = [
    L("8.1", "What Is an ESB?", M08_MOD,
      ["Define an Enterprise Service Bus as a centralized mediation hub.",
       "List routing, transformation, protocol bridging, and orchestration as typical bus jobs.",
       "Separate the useful pattern (anti-corruption, adapter) from the organizational failure mode (the bus team owns every mapping)."],
      "Northbridge’s “integration” is a cluster that every project waits on. New products queue for six weeks to get an ESB mapping. The bus solved 2008’s protocol zoo and created 2026’s bottleneck.",
      "An ESB is a **hub** that sits between applications to route, transform, and mediate protocols so endpoints do not couple directly. It was a rational response to SOAP, MQ, FTP, and vendor adapters. It becomes harmful when it is the only place business logic can change, when every team must release through one pipeline, and when the canonical model is a political object. Architects must understand ESBs well enough to modernize them—not parody them.",
      ["You inherit one.",
       "A protocol cannot be changed this year (adapter).",
       "A regulated transformation must stay in a controlled layer temporarily."],
      ["Greenfield service-to-service JSON inside one domain.",
       "Using a new ESB to avoid designing APIs and events."],
      "Draw the bus as: endpoints, adapters, canonical messages, routing rules, transformation maps, operational console. Identify which of those you still need (adapters) versus which you will distribute (routing via events, transforms in services).",
      "There is no single “AWS ESB.” People simulate one with a mega Lambda, an iPaaS, or EventBridge-plus-everything. Resist the simulation. Use adapters (containers, commercial connectors) at the edge and distributed patterns inside.",
      "If you were forbidden from adding a mapping for 90 days, which business changes would halt? That is the coupling cost of the bus.",
      diagram="flowchart LR\n  A[App A] --> ESB[ESB hub]\n  B[App B] --> ESB\n  C[App C] --> ESB\n  P[Partner FTP] --> ESB\n  ESB --> A\n  ESB --> B\n  ESB --> C",
      tradeoffs=[("Hub", "Fewer pairwise protocols", "Central bottleneck and coupling"),
                 ("Distributed", "Team autonomy", "Need contracts and platform skill")],
      checks=[{"q": "What problem did the ESB originally solve?", "a": "N-squared protocol and mapping connections among heterogeneous enterprise systems."}],
      anti_patterns=["Rewriting the ESB in Lambda and calling it cloud-native.", "Pretending the bus does not exist in the inventory."],
      architect_note="Respect the bus: it still moves money. Modernize with a strangler, not a sneer."),
    L("8.2", "Enterprise Integration History", M08_MOD,
      ["Place RPC, EDI, EAI, SOA/ESB, microservices, iPaaS, and events on a timeline of problems—not fashion.",
       "Explain why each wave left residue in the estate.",
       "Use history to talk to executives who bought the last wave."],
      "A steering committee wants “to skip to agents.” The estate still has EDI, a SOAP bus, and REST. History tells you you will wrap, not skip.",
      "EDI and files connected companies before the internet was a product. EAI tools mapped packaged apps. SOA/ESB promised reuse via a hub. Microservices promised autonomous deploys. iPaaS promised faster maps in the cloud. Events promised decoupling. Agents now promise natural language. Each wave addresses a real pain and leaves **residue**: skills, contracts, vendors, and risk. Architects sequence coexistence.",
      ["Executive education.",
       "Migration roadmaps.",
       "Vendor evaluations."],
      ["Using history to mock the current operations team.",
       "Assuming the newest wave deletes the others this quarter."],
      "Inventory which wave each integration belongs to. Do not mix layers accidentally (agent writing to EDI without a tool). Roadmap: stabilize, expose, strangler, decommission.",
      "AWS itself is multi-wave: Transfer Family (files), API Gateway (API), EventBridge (events), Bedrock (agents). The platform is a timeline. Use it as such.",
      "Why would an agent project fail if EDI still is the legal contract with a supplier?",
      diagram="flowchart LR\n  EDI[EDI / files] --> EAI[EAI]\n  EAI --> ESB[SOA / ESB]\n  ESB --> MS[Services / APIs]\n  MS --> EV[Events]\n  EV --> AG[Governed agents]",
      tradeoffs=[("Coexistence", "Lower risk", "More complexity now"),
                 ("Big bang rewrite", "Clean story", "Outage and budget risk")],
      checks=[{"q": "What is residue?", "a": "Contracts, skills, vendors, and systems that remain after the next architectural wave is announced."}],
      anti_patterns=["Greenfield-only diagrams presented as current state.", "Agent washing the ESB."],
      architect_note="Your job is often translation between waves, not purity."),
    L("8.3", "Routing on a Bus", M08_MOD,
      ["Describe content-based and address-based routing in a hub.",
       "Show how routing tables become untestable.",
       "Compare hub routing to EventBridge rules and to service-owned routing."],
      "A single routing artifact with 4,000 paths cannot be code-reviewed. Production is the test. That is why distributed routing is attractive—and why you must not recreate 4,000 EventBridge rules without tests.",
      "Buses route by address, header, or payload. Central routing gives a single place to look and a single place to break. Distributed routing (each service subscribes) scales ownership but needs discovery and schema discipline.",
      ["When endpoints cannot change and a hub already routes.",
       "When a temporary anti-corruption layer must send to the right legacy program."],
      ["Growing the central table as the default for every new microservice."],
      "If you keep hub routing, treat it as code: version, test, review. If you move to events, move **ownership** of subscriptions with the consumer. Measure path count.",
      "EventBridge rules, API Gateway routes, Step Functions choices—all can become mini-buses. Apply the same hygiene.",
      "Who is paged when a routing change drops payments but not email?",
      diagram="flowchart TB\n  In[Message in] --> R{Router}\n  R --> L[Legacy A]\n  R --> S[SaaS B]\n  R --> Q[Queue C]",
      tradeoffs=[("Central router", "Visibility of paths", "Change contention"),
                 ("Consumer subscription", "Autonomy", "Harder global picture unless you inventory")],
      checks=[{"q": "What makes a routing table untestable?", "a": "Volume of undocumented, environment-specific, payload-parsed paths without fixtures."}],
      anti_patterns=["Routing in production-only XML.", "Copying the XML into Lambda unchanged."],
      architect_note="Path count is a modernization KPI."),
    L("8.4", "Transformation", M08_MOD,
      ["Place transformation at anti-corruption boundaries.",
       "Warn against a single canonical transform for all meanings.",
       "Prefer explicit maps in versioned code over opaque GUI maps."],
      "The bus maps “customer” 70 ways. Nobody knows which map finance uses. Transformation without tests is a silent ledger bug.",
      "Transformation is necessary because schemas differ. It is dangerous because it can change meaning (amount in cents vs dollars). Own maps with the boundary that understands both sides, version them, test with golden files, and log both sides’ IDs.",
      ["Protocol/schema edges you do not control.",
       "Partner files to internal events."],
      ["Transforming inside the core domain for every consumer’s whim (that is an API product problem).",
       "Lossy maps that drop audit fields."],
      "Anti-corruption layer (ACL): inbound map to domain, outbound map to partner. Golden tests. Do not dual-write two meanings of amount.",
      "Lambda/ESB maps, Glue for analytics (different purpose). Keep payment transforms in tightly reviewed code with fixtures in sample-data.",
      "If a map changes 100.00 to 10000 “for the mainframe,” where is that documented and tested?",
      diagram="flowchart LR\n  Ext[External schema] --> ACL[Anti-corruption map]\n  ACL --> Dom[Domain model]\n  Dom --> Out[Outbound map]\n  Out --> Prt[Partner schema]",
      tradeoffs=[("Central maps", "Reuse", "Meaning collisions"),
                 ("Per-boundary maps", "Clear meaning", "Some duplication")],
      checks=[{"q": "What is an anti-corruption layer?", "a": "A boundary that translates another system’s model without letting that model leak into your domain."}],
      anti_patterns=["GUI mapping with no git history.", "Silent default values for missing amounts."],
      architect_note="Golden file tests are cheaper than reconciliation incidents."),
    L("8.5", "Protocol Mediation", M08_MOD,
      ["Treat adapters as first-class: SOAP, MQ, SFTP, FHIR, ISO 20022.",
       "Do not require partners to speak your internal protocol.",
       "Keep adapters thin: protocol in, domain message out."],
      "A plant speaks OPC-UA. Finance speaks SFTP. The agent speaks HTTPS. Mediation is how they coexist. The mistake is a thick adapter that also prices orders.",
      "Protocol mediation converts transport and framing, not business policy. Thin adapters: terminate SOAP, emit an internal command/event. Thick adapters become another ESB. Inventory protocols in the integration catalog.",
      ["Any legacy or partner protocol you cannot retire this year.",
       "When a strangler needs a façade."],
      ["New internal services inventing SOAP “for consistency with 2009.”",
       "Business rules in the adapter."],
      "One adapter per protocol family where possible. Health checks. Separate deploy from domain services. Capstone 4 still needs an ERP adapter.",
      "API Gateway for HTTP façades, Transfer Family for SFTP, MQ on EC2/Amazon MQ for JMS, FHIR APIs for health. Amazon does not erase HL7 v2 in a hospital; an adapter does.",
      "Should the adapter or the domain service own duplicate detection?",
      diagram="flowchart LR\n  SOAP[SOAP] --> Ad[Thin adapter]\n  SFTP[SFTP] --> Ad2[Thin adapter]\n  Ad --> Int[Internal event/command]\n  Ad2 --> Int",
      tradeoffs=[("Thin adapter", "Replaceable", "Domain must still validate"),
                 ("Thick adapter", "Fast field mapping", "Hidden business logic")],
      checks=[{"q": "What should a thin adapter not do?", "a": "Credit decisions, pricing, or other domain policy."}],
      anti_patterns=["One “universal adapter” microservice.", "Plant protocol terminated on a laptop."],
      architect_note="Adapters are how honesty about residue looks in an architecture diagram."),
    L("8.6", "Canonical Data Models", M08_MOD,
      ["Use canonical models narrowly or not at all.",
       "Prefer published language at the boundary.",
       "Show how a global Customer object becomes a committee."],
      "The enterprise Customer canonical type took 18 months and still fit no mobile screen. Canonical models are gravity wells.",
      "A canonical model is a shared representation all parties map to. It reduces N×N maps to N×2 in theory. In practice, competing meanings stall change. Prefer **bounded published events/APIs** per domain, with maps at edges. A small canonical for a specific network (payments ISO, FHIR resources) is different from a company-wide über-object.",
      ["Industry standards you should not reinvent (FHIR, ISO 20022) as *external* published language.",
       "A small hub with truly identical semantics."],
      ["A single object for all meanings of customer, order, and product across 80 apps.",
       "Blocking delivery until the canonical is finished."],
      "If you inherit a canonical, freeze it, wrap it, and stop extending it except for compliance. New domains publish their own contracts.",
      "Event schemas and OpenAPI are published language. Do not create a DynamoDB “canonical table” everyone writes.",
      "FHIR as canonical for health interoperability vs an internal über-Patient table: which is a standard and which is a swamp?",
      diagram="flowchart TB\n  subgraph Bad\n  A1[Apps] --> Can[Global canonical]\n  end\n  subgraph Better\n  A2[Apps] --> Pub[Published domain contracts]\n  end",
      tradeoffs=[("Canonical hub", "Fewer maps in theory", "Slow politics"),
                 ("Domain contracts", "Speed", "Some translation")],
      checks=[{"q": "When is a canonical model justified?", "a": "When semantics truly match or an industry standard already is the language—not as a hope to unify politics."}],
      anti_patterns=["Canonical field “misc.”", "Stopping APIs until the model is perfect."],
      architect_note="Industry standards ≠ your internal ER diagram. Do not confuse them."),
    L("8.7", "Service Orchestration on the Bus", M08_MOD,
      ["Distinguish orchestration (a conductor) from choreography (events).",
       "Show why the ESB became a process engine.",
       "Place sagas in visible workflow tools, not hidden maps."],
      "Order-to-cash on the bus calls seven systems synchronously. One timeout rolls up as “ESB down.” Orchestration without isolation is a distributed monolith.",
      "Orchestration is useful when the process is the product (onboarding, claims adjudication) and compensations are required. The ESB often hid these processes in proprietary flows. Modernization should **make the process visible** (state machine) and **keep steps idempotent**, not delete process.",
      ["Long-running processes with branches and human tasks.",
       "When choreography would obscure legal sequence."],
      ["Every CRUD as a process.",
       "Orchestrating independent notifications that should be events."],
      "Choose choreography for independent facts; orchestration for a business transaction with a completion state. Module 10 sagas. Lab 8 asks what stays on a conductor.",
      "Step Functions vs EventBridge-only. iPaaS process designers. The AWS name is not the point; visibility and compensations are.",
      "Should “email the receipt” be a step in the orchestrator or a subscriber to OrderCompleted?",
      diagram="flowchart TB\n  Orch[Orchestrator] --> P[Pay]\n  Orch --> I[Inventory]\n  Orch --> N[Notify]\n  P --> Orch\n  I --> Orch",
      tradeoffs=[("Orchestration", "Visible sequence and compensations", "Conductor as coupling point"),
                 ("Choreography", "Independence", "Harder to see the process")],
      checks=[{"q": "What is a distributed monolith?", "a": "Independently named services that can only change or stay up together because of a hidden central process or data model."}],
      anti_patterns=["Sync fan-out from the bus to seven systems with one timeout.", "Process XML that nobody can diff."],
      architect_note="If the process is legally load-bearing, it deserves a diagram and tests, not a hidden map."),
    L("8.8", "Problems with Centralized ESB Architectures", M08_MOD,
      ["Name bottlenecks, coupling, governance overhead, scaling, and deployment dependencies.",
       "Turn problems into modernization drivers with metrics.",
       "Avoid blaming individuals who kept the lights on."],
      "Every release of the bus stops unrelated projects. Weekend change freezes. This is the problem list you will use in Lab 8’s ADR.",
      "Bottlenecks: finite bus team throughput. Coupling: shared canonical and shared runtime. Governance overhead: CAB for a field map. Scaling: vertical or awkward clustering. Deployment dependencies: one bad map breaks many flows. Cost: licenses plus delay. These are **architectural** problems. The people operating the bus are often the only reason the company still settles.",
      ["Justifying a strangler.",
       "Setting KPIs: lead time for a new mapping, incident blast radius, deploy coupling."],
      ["Big-bang rewrite as the first move.",
       "No metrics, only aesthetics (“not cloud”)."],
      "Measure mapping lead time, change failure rate, blast radius. Pick strangler candidates: high-change, low-risk flows first. Keep the bus for low-change protocol edges. That is Module 9.",
      "Moving to API Gateway/EventBridge/SQS does not automatically fix governance. You can rebuild the bottleneck as a central “platform PR required for every schema.” Design federated contracts.",
      "Which two metrics would you put on an executive slide to fund modernization?",
      diagram="flowchart TB\n  Teams[Many product teams] --> BusTeam[One bus team]\n  BusTeam --> Runtime[Shared runtime]\n  Runtime --> All[All flows]",
      tradeoffs=[("Keep ESB forever", "Predictable to incumbents", "Delay and concentration risk"),
                 ("Modernize", "Autonomy and scale", "Need skills and dual-run")],
      checks=[{"q": "Name five centralized ESB problems from this lesson.", "a": "Bottlenecks, coupling, governance overhead, scaling limits, deployment dependencies (blast radius)."}],
      anti_patterns=["Modernization with no KPI.", "Cutting over the settlement flow first to “prove value.”"],
      architect_note="Lab 8’s ADR should quote this problem list with numbers, even if estimated."),
]

M09 = [
    L("9.1", "From Hub to Distributed Cloud Integration", M09_MOD,
      ["Sketch the target: APIs, events, queues, files, thin adapters.",
       "Keep the bus where it still earns its place.",
       "Use cloud services as implementations of styles, not as the strategy."],
      "Leadership wants “all on EventBridge by December.” Settlement is still ISO on MQ. A target that ignores residue is a fantasy.",
      "The target architecture is a **platform of styles**: API products, event backbone, work queues, file landing, and a shrinking adapter tier. Cloud mappings: API Gateway, EventBridge, SQS, S3/Transfer, containers for leftover protocols, Step Functions for visible orchestration. The strategy is distribution of ownership, not a new hub brand.",
      ["Any ESB modernization program.",
       "When new domains should not be allowed onto the bus."],
      ["A second ESB in the cloud.",
       "Forcing MQ partners to REST in one quarter."],
      "Draw current (apps → ESB → apps) and target (apps → style-appropriate edges). Policy: new integrations cannot add bus maps without an exception ADR. Platform teams provide golden paths.",
      "The AWS list in the course spec is the toolbox. Lab 8 uses it to redesign a given legacy diagram.",
      "What remains on the bus in 18 months, and who pays for that remaining license?",
      diagram="flowchart LR\n  subgraph Today\n  A1[Apps] --> ESB[ESB]\n  ESB --> A2[Apps]\n  end\n  subgraph Target\n  B1[Apps] --> API[APIs]\n  B1 --> EV[Events]\n  B1 --> Q[Queues]\n  B1 --> F[Files]\n  Ad[Adapters] --> EV\n  end",
      tradeoffs=[("Distributed styles", "Autonomy", "Need platform + skills"),
                 ("Cloud hub iPaaS as new ESB", "Familiar ops", "Same bottleneck in a new bill")],
      checks=[{"q": "What is the policy that actually changes behavior?", "a": "New work defaults off the bus; exceptions require ADRs—not a slide that says “event-driven.”"}],
      anti_patterns=["Lift the ESB to a VM in AWS.", "EventBridge as the new canonical model committee."],
      architect_note="Target state is a portfolio, not a single service."),
    L("9.2", "Strangler Fig for Integrations", M09_MOD,
      ["Apply strangler: façade, intercept, replace, shrink.",
       "Pick candidate flows with risk × change rate.",
       "Keep dual-run and comparison for money flows."],
      "A team rewired settlement first because it was “the most important.” They learned why stranglers start at the edges.",
      "The strangler fig pattern wraps a legacy system with a façade, migrates capabilities incrementally, and shrinks the legacy. For ESBs, the façade may be an API or file gateway that still calls the bus internally, then one flow at a time moves to native cloud integration. Dual-run and reconcilers protect correctness.",
      ["Any production bus you cannot stop.",
       "When you can intercept at a protocol edge."],
      ["Rewriting all maps offline for a weekend cutover as plan A.",
       "Strangling without traffic metrics."],
      "Steps: inventory, façade, choose a low-blast high-learning flow, dual-run, switch reads, switch writes, remove map, repeat. Lab 8 requires a strangler sequence in the ADR.",
      "API Gateway as façade, feature flags in DynamoDB, shadow traffic to new SQS path, reconcilers in S3/Athena if needed. Keep Transfer Family façade if SFTP is the intercept point.",
      "Order the strangler of: (a) marketing email, (b) card settlement, (c) partner SFTP catalog. Why that order?",
      diagram="flowchart TB\n  Cons[Consumers] --> F[Façade]\n  F --> ESB[Legacy ESB]\n  F --> New[New path]\n  New --> Dom[Services]\n  ESB -.->|shrink| X[Decommission maps]",
      tradeoffs=[("Strangler", "Safer", "Dual-run cost"),
                 ("Cutover", "Fast if it works", "High ruin probability")],
      checks=[{"q": "What is shadow traffic?", "a": "Sending a copy of production inputs to the new path without taking the production write, then comparing outcomes."}],
      anti_patterns=["No rollback for the façade.", "Calling the project done when 10% of maps remain but they are the money maps."],
      architect_note="The last 10% of maps are often the reason the bus exists. Plan them; do not forget them."),
    L("9.3", "What Stays, What Changes, Why", M09_MOD,
      ["Build a keep/change/retire table for an ESB estate.",
       "Justify each row with NFRs, not taste.",
       "Identify migration risks explicitly."],
      "Lab 8’s entire point. Students who “move everything to Lambda” fail the ADR.",
      "Keep: stable protocol adapters with few changes, certified transforms, low-churn partner maps. Change: high-churn digital products, new domains, anything blocked by bus lead time. Retire: duplicate maps, dead partners, canonical fields nobody reads. Risks: dual meaning of amounts, unidentified consumers, license terms, staff skills, undetected point-to-point that bypasses the bus already.",
      ["Every modernization ADR.",
       "Vendor renewal conversations."],
      ["Keep/change decided by who shouts.",
       "Retire without a consumer inventory."],
      "Table columns: flow, style now, style later, keep/change/retire, risk, measure of done. Lab 8 uses this table.",
      "Technology later: maybe Amazon MQ remains for a plant, Transfer Family for SFTP, EventBridge for digital facts. The table comes first.",
      "Pick one flow you would keep on an adapter for 24 months and defend it.",
      diagram="flowchart LR\n  Inv[Inventory] --> T{Decision}\n  T --> K[Keep adapter]\n  T --> C[Change to API/event/file platform]\n  T --> R[Retire]",
      tradeoffs=[("Keep adapters", "Risk down", "License lingers"),
                 ("Change digital first", "Visible wins", "Bus still critical")],
      checks=[{"q": "Why might a stable ISO20022 MQ flow stay?", "a": "Low change rate, high correctness risk, certified mapping, partner cannot move—NFR-driven keep."}],
      anti_patterns=["Retire column empty.", "Change column = everything."],
      architect_note="This table is the Lab 8 deliverable. Quality here matters more than Terraform."),
    L("9.4", "Migration Risks and Dual-Run", M09_MOD,
      ["List semantic drift, missed consumers, replay, identity, and operational skill as risks.",
       "Design dual-run with comparison metrics.",
       "Budget a hypercare period."],
      "New path posted cents; bus posted dollars. Dual-run without comparison is two wrongs.",
      "Risks: semantic drift in maps, consumers you did not know (they subscribed to the bus in 2014), identity differences (bus service account vs IAM), poison handling differences, replay differences, observability gaps, cost spikes, staff who only know the bus tool. Mitigations: inventory, dual-run, reconcilers, feature flags, training, kill-switch back to bus.",
      ["Any money, identity, or clinical flow.",
       "Any flow with unknown subscribers."],
      ["Dual-run forever as a lifestyle.",
       "Comparison only of counts, not amounts."],
      "Compare: record counts, hash of key fields, amount totals, latency, error codes. Alert on drift. Time-box dual-run. Hypercare staffing. ADR lists risks and mitigations—Lab 8 requires this section.",
      "Two DynamoDB tables or a recon file in S3. Lambda comparer. CloudWatch metrics DriftCount. Kill-switch parameter.",
      "What kill-switch granularity do you need: per flow, per partner, or global?",
      diagram="flowchart LR\n  In[Input] --> Bus[Legacy]\n  In --> New[New path]\n  Bus --> Cmp[Comparer]\n  New --> Cmp\n  Cmp --> M[Drift metrics]",
      tradeoffs=[("Dual-run", "Evidence", "Double cost and dual bugs"),
                 ("Instant switch", "Cheap", "Undetected semantic bugs")],
      checks=[{"q": "Why are counts insufficient comparison?", "a": "You can have the same number of rows with wrong amounts or swapped accounts."}],
      anti_patterns=["No kill-switch.", "Turning off bus logs to save money during dual-run."],
      architect_note="Dual-run is a scientific experiment. Write the hypothesis: “new path matches bus within $0.01 per day.”"),
    L("9.5", "Lab 8 Preview — Redesign and ADR", M09_MOD,
      ["Know the Lab 8 artifacts before opening the lab.",
       "Refuse a single “target architecture” dump without keep/change.",
       "Practice defending tradeoffs as if in an ARB."],
      "Students receive a messy ESB diagram. The lab does not give the answer. This lesson tells you what “done” looks like.",
      "Done: current-state inventory, NFR table, keep/change/retire, strangler waves, target diagram using styles, AWS mapping as a *consequence*, risks, dual-run, cost, operations, security, and a full ADR. Implementation of a slice is optional extra; the architecture grade is the point.",
      ["Before Lab 8.",
       "Before each capstone (same muscle)."],
      ["Copying a reference architecture from the internet as the submission."],
      "Use the ADR template in templates/adr.md. Use the decision framework. Expect challenge questions: why not EventBridge for the 20 GB file? why not keep the bus for mobile? Answer with NFRs.",
      "If you implement a slice, small Terraform is enough. Do not boil the ocean in the lab window.",
      "What would cause the ARB to reject your Lab 8 even if the diagram is pretty?",
      diagram="flowchart TB\n  AsIs[As-is ESB] --> Inv[Inventory]\n  Inv --> ADR[ADR]\n  ADR --> Waves[Strangler waves]\n  Waves --> ToBe[To-be styles]",
      tradeoffs=[("Architecture-first lab", "Matches EA job", "Less time clicking AWS"),
                 ("Build-first", "Demo", "Shallow decisions")],
      checks=[{"q": "Name the Lab 8 mandatory sections.", "a": "What stays, what changes, why, migration risks, strangler strategy—plus a complete ADR."}],
      anti_patterns=["No as-is diagram.", "To-be that still is a hub with extra AWS logos."],
      architect_note="If you cannot defend it aloud, it is not done. Module 14 will make you do this under time pressure."),
]

# 17 EIP lessons
def eip(num, name, problem, when, when_not, aws, decision, extra_why=""):
    return L(
        f"10.{num}",
        name,
        M10_MOD,
        [f"Explain the problem {name} solves.",
         "Draw a vendor-neutral architecture for the pattern.",
         "Choose when not to use it and map a sensible AWS example."],
        f"Harbor/Northbridge incident: {problem}",
        (f"{name} exists because {problem} The pattern is a known, named response so architects can debate tradeoffs instead of inventing folklore. "
         + extra_why),
        when,
        when_not,
        f"**Pattern:** {name}. Structure the design so the problem cannot recur silently. Include failure behavior in the diagram. "
        f"Teach the pattern in reviews by name so teams share vocabulary.",
        f"**AWS example (after the pattern):** {aws}",
        decision,
        diagram="flowchart LR\n  P[Problem] --> Pat[Pattern: " + name + "]\n  Pat --> Out[Controlled outcome]",
        tradeoffs=[("Apply pattern", "Known failure modes", "Over-engineering if the problem is absent"),
                   ("Ignore", "Faster demo", "Recurring incident class")],
        checks=[{"q": f"In one sentence, what problem does {name} solve?", "a": problem}],
        anti_patterns=[f"Using {name} as decoration without the problem present.", "Renaming the pattern every project."],
        architect_note="Every pattern in this module must appear in at least one capstone ADR by name.",
        nfr=["Problem presence", "Cost of the pattern", "Ops skill"],
    )

M10 = [
    eip(1, "Request/Reply",
        "A caller needs an answer in-band (quote, balance, validation errors).",
        ["Immediate response, known provider, modest payload."],
        ["Long processing, fan-out facts, huge files."],
        "API Gateway + Lambda; or SQS + reply queue if you must decouple but still correlate a response.",
        "Is a 40-second configurator request/reply or accepted+status?"),
    eip(2, "Fire and Forget",
        "The producer must not wait, and no in-band result is required.",
        ["Audit pings, non-critical notifications already covered elsewhere."],
        ["Money movement, anything you will have to reconcile."],
        "SQS with a worker; SNS when it is truly a notification. Still include IDs for trace.",
        "Is “charge the card” ever fire-and-forget?"),
    eip(3, "Queue-Based Load Leveling",
        "Producers burst faster than consumers can safely run.",
        ["Spiky ingest, licensed downstream TPS, batching workers."],
        ["When latency SLO cannot absorb the queue delay."],
        "SQS + limited Lambda concurrency or ECS service with a max.",
        "What lag SLO makes this pattern honest rather than a hidden outage?"),
    eip(4, "Publish/Subscribe",
        "Many independent consumers need the same fact/notification.",
        ["OrderCreated fan-out, AddressChanged."],
        ["A single worker command; a process that needs compensations as one unit without a saga design."],
        "SNS + SQS; or EventBridge rules to multiple targets.",
        "How do you keep a new subscriber from requiring a producer change?"),
    eip(5, "Content-Based Router",
        "The next destination depends on message content.",
        ["File type routing, country-specific payments, tenant routing."],
        ["When routing encodes a whole saga; when content is highly sensitive."],
        "EventBridge patterns; Step Functions Choice; a routing table in DynamoDB.",
        "Should PAN or diagnosis appear in the routing key?"),
    eip(6, "Message Filter",
        "A consumer should not receive what it cannot or must not see.",
        ["Analytics ignoring test orders; dropping health events a system is not authorized for."],
        ["Filter as the only authorization; undocumented filters."],
        "SNS filter policies; EventBridge patterns.",
        "How do you test that a filter did not silently drop production traffic?"),
    eip(7, "Message Translator",
        "Two systems speak different schemas.",
        ["Partner file to internal event; FHIR to internal model at the edge."],
        ["Translating away audit meaning; untested GUI maps."],
        "Lambda/ACL; dedicated mapper with golden tests; not the API Gateway as a general mapper.",
        "Where do you keep golden fixtures?"),
    eip(8, "Aggregator",
        "You must combine related messages into one result.",
        ["Split batches coming back together; scatter/gather joins."],
        ["Aggregating unbounded streams without a window; holding GB in memory."],
        "Step Functions; DynamoDB as aggregate store with TTL; SQS FIFO grouping when appropriate.",
        "What completion condition ends the aggregate if a part never arrives?"),
    eip(9, "Splitter",
        "A composite message must be processed per part.",
        ["File to per-row commands; order to per-line inventory checks."],
        ["Splitting without correlation IDs; exploding 10M messages without back-pressure."],
        "Lambda chunker + SQS; Step Functions Map (with limits).",
        "How do you cap Map concurrency to protect a 50 TPS downstream?"),
    eip(10, "Scatter/Gather",
        "You must ask several providers and combine answers.",
        ["Quote from three carriers; availability from multiple warehouses."],
        ["When a single source of truth exists; unbounded fan-out of PII."],
        "Step Functions parallel branches; async requests with an aggregator.",
        "What do you return if one of three carriers times out?"),
    eip(11, "Claim Check",
        "The payload is too large or sensitive to travel on the bus.",
        ["Large files; images; optionally PHI stored aside with a pointer."],
        ["Claim-checking tiny JSON as ceremony; pointers without authz."],
        "S3 object + event/message with bucket/key/version/checksum.",
        "What travels on EventBridge for a 10 GB object?"),
    eip(12, "Saga",
        "A business transaction spans systems without a distributed ACID transaction.",
        ["Order + pay + reserve; compensating on failure."],
        ["A single-system local transaction; pretending saga means “lots of events” with no compensations."],
        "Step Functions (orchestration) or choreography with explicit compensation events.",
        "Payment succeeds, inventory fails: what compensation runs, and is it idempotent?"),
    eip(13, "Circuit Breaker",
        "Repeated calls to a failing dependency would amplify the outage.",
        ["Downstream 500s/timeouts; protecting your thread/concurrency pool."],
        ["Using it to hide a missing SLA; open circuit with no UX/status."],
        "In-process breaker in the worker; API Gateway/App Mesh-like patterns; degrade to queue.",
        "What does the user see when the fraud circuit is open?"),
    eip(14, "Retry",
        "Transient faults should not fail the business operation.",
        ["Network blips, 429, 503."],
        ["Poison schema; unbounded retry; retrying non-idempotent posts without keys."],
        "SDK retries + SQS redrive + backoff/jitter (Module 11). Count them.",
        "How many total attempts exist if SDK, Lambda, and SQS all retry?"),
    eip(15, "Dead Letter Queue",
        "Poison or exhausted messages must not block or vanish.",
        ["After max attempts; operator inspect and replay."],
        ["DLQ as trash; no alarms; purge to green."],
        "SQS redrive; Lambda destinations; EventBridge DLQ.",
        "What are inspect, fix, replay, and who is paged?"),
    eip(16, "Idempotent Consumer",
        "At-least-once delivery would otherwise duplicate side effects.",
        ["Every payment, order, file post, reservation."],
        ["Idempotency store with TTL shorter than the retry window; in-memory sets on Lambda."],
        "DynamoDB conditional writes keyed by message/event/file ID.",
        "Same event ID twice: what happens to money?"),
    eip(17, "Compensating Transaction",
        "A completed step must be undone when a later step fails.",
        ["Saga undo: refund, release inventory, cancel shipment."],
        ["Compensation that is not idempotent; compensating what never happened; hoping DELETE is enough for money."],
        "Explicit compensating APIs/commands from Step Functions catch blocks; events like InventoryReleased.",
        "Is compensation a refund API or a “negative quantity” event—and how do you audit it?",
        extra_why="Compensation is not rollback of a local DB transaction; it is a new business action with its own contract."),
]
